AWSTemplateFormatVersion: 2010-09-09
Description: My Sample EC2 Template
Parameters:
  EBSSize:
    Type: String
  InstanceName:
    Type: String
  ProjectName:
    Type: String
  InstanceType:
    Type: String
  KeyName:
    Type: String
  Public1Subnet:
    Type: String
  SecurityGroupCloudpack:
    Type: String
  SecurityGroupOwner:
    Type: String
  SecurityGroupWeb:
    Type: String
Outputs:
  WebServers:
    Value:
      Ref: WebServers
Resources:
  WebServerEIP:
    Properties:
      Domain: vpc
      InstanceId:
        Ref: WebServers
    Type: AWS::EC2::EIP
  WebServerIAMInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: WebServerIAMRole
    Type: AWS::IAM::InstanceProfile
  WebServerIAMRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Path: /
    Type: AWS::IAM::Role
  WebServers:
    Properties:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize:
            Ref: EBSSize
      IamInstanceProfile:
        Ref: WebServerIAMInstanceProfile
      ImageId: ami-eec1c380
      InstanceType:
        Ref: InstanceType
      SubnetId:
        Ref: Public1Subnet
      SecurityGroupIds:
        - Ref: SecurityGroupCloudpack
        - Ref: SecurityGroupOwner
        - Ref: SecurityGroupWeb
      KeyName:
        Ref: KeyName
      Tags:
      - Key: Name
        Value:
          Ref: InstanceName
      - Key: Backup-Generation
        Value: "2"
      UserData:
        Fn::Base64:
          Fn::Join:
          - ""
          - - |
              #!/bin/sh
            - |
              yum update -y
            - |
              yum install epel-release -y
            - |
              yum install gcc python-devel python-crypto python-pip git -y
            - |
              easy_install pip
            - |
              pip install ansible
            - |
              cd ~
            - |
              git clone https://github.com/shogomuranushi/muranotemplate2.git
            - |
              sleep 30
            - |
              ansible-playbook muranotemplate2/ansible/main.yml
            - |
              ansible-playbook muranotemplate2/ansible/nrpe.yml --extra-vars 'nagiosserver=,11.22.33.44'
            - |
              cat <<EOF > muranotemplate2/ansible/roles/apache/vars/main.yml
            - |
              site:
            - |2
               - { domain: 'www.test1.com', owner: 'root' }
            - |2
               - { domain: 'www.test2.co.jp', owner: 'apache' }
            - |
              EOF
            - |
              ansible-playbook muranotemplate2/ansible/apache.yml
            - |
              ansible-playbook muranotemplate2/ansible/vsftpd.yml --extra-vars 'eip=22.33.44.55'
            - |
              ansible-playbook muranotemplate2/ansible/php.yml
            - |
              ansible-playbook muranotemplate2/ansible/selenux-desable.yml
    Type: AWS::EC2::Instance
